// 1.  import area

// Import DefaultImport from 'some library/location';

import Head from 'next/head'      // This is coming from node_module.
import styles from '../styles/Home.module.css'    //  This is coming from relative address.
import A from '../components/A';

// 2.  Definition area

 function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <A name="anita" msg="OKLABS"> </A>
    </div>
  )
}

// 3.  export area

export default Home;